export enum queryKeys {
  USER = "USER",
  MAIN = "MAIN",
  NOTICE = "NOTICE",
  EVENT = "EVENT",
  MATCHING = "MATCHING",
  COMMUNITY = "COMMUNITY",
  COMMUNITY_COMMENT = "COMMUNITY_COMMENT",
  COMMUNITY_REPLY = "COMMUNITY_REPLY",
}
